# Generated by Django 2.2.1 on 2019-05-07 18:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('TelCelular', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular')),
                ('TelFixo', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone fixo')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=1, verbose_name='Estado civil')),
                ('email', models.EmailField(max_length=254)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('login', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.IntegerField(blank=True, null=True)),
                ('curriculo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('criadoData', models.DateTimeField()),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='funcionario',
            managers=[
            ],
        ),
    ]
